// Built-in exercise library. Anything added or edited in the app's Gym tab is saved to the
// shared database and layered on top of this list (same id = your version wins).

export const GYM = { name: "Planet Fitness Kirkwood", maxDumbbell: 50 };

export const EQUIP = { dumbbell: "Dumbbells", machine: "Machine", cable: "Cable", barbell: "Smith / barbell", bodyweight: "Bodyweight", cardio: "Cardio machine", other: "Other" };
export const PATTERN = { push: "Push", pull: "Pull", squat: "Squat", hinge: "Hinge", lunge: "Lunge", carry: "Carry", rotation: "Rotation", core: "Core", isolation: "Isolation", power: "Power" };
export const JOINTS = { neck: "Neck", shoulders: "Shoulders", elbows: "Elbows", wrists: "Wrists", lowerBack: "Lower back", hips: "Hips", knees: "Knees", ankles: "Ankles & feet" };
export const POSITION = { standing: "Standing", seated: "Seated", lying: "Lying on a bench", floor: "On the floor", bent: "Bent over" };
export const LEVEL = { difficulty: ["", "Beginner", "Intermediate", "Advanced"], effort: ["", "Light", "Moderate", "Hard"], impact: ["None", "Low", "High"] };

// L(id, name, focus, pattern, [difficulty 1-3, effort 1-3, impact 0-2], position, joints {area: 1 some | 2 high}, sr, how, risks [[area, what can go wrong, how to avoid]], extra)
const L = (id, name, focus, pattern, [difficulty, effort, impact], position, joints, sr, how, risks, o = {}) => ({
  id, name, equip: o.equip || "dumbbell", focus, focus2: o.focus2 || [], pattern, difficulty, effort, impact, position,
  unilateral: !!o.uni, joints, sr, how, risks: risks.map(([area, risk, avoid]) => ({ area, risk, avoid })),
  kind: o.kind || "load", db: o.db !== false, heavy: o.heavy || "", builtin: true
});

export const BUILTIN = [
  // ---------------- chest
  L("db-bench-press", "Dumbbell Bench Press", ["chest"], "push", [1, 2, 0], "lying", { shoulders: 1, elbows: 1, wrists: 1 }, "3 × 8–12",
    "Lie on a flat bench, dumbbells over your chest. Lower to the sides of your chest, then press back up until the dumbbells nearly touch.",
    [["shoulders", "Front-of-shoulder strain or pinching", "Keep elbows about 45° from your body, not flared straight out, and stop when the dumbbells reach chest level."],
     ["wrists", "Wrist strain", "Keep wrists straight and stacked over your elbows."],
     ["shoulders", "Shoulder injury getting into or out of position", "Rest the dumbbells on your thighs, then roll back with them held to your chest. Never drop them out to the sides."]],
    { focus2: ["shoulders", "arms"] }),
  L("db-incline-press", "Incline Dumbbell Press", ["chest"], "push", [1, 2, 0], "lying", { shoulders: 2, elbows: 1, wrists: 1 }, "3 × 8–12",
    "Bench at about 30°. Lower the dumbbells to your upper chest and press up and slightly together.",
    [["shoulders", "Shoulder impingement, which gets worse at steeper angles", "Keep the bench at 30° or lower and tuck your elbows slightly."],
     ["wrists", "Wrist strain", "Wrists straight, knuckles pointing up."]],
    { focus2: ["shoulders", "arms"] }),
  L("db-floor-press", "Dumbbell Floor Press", ["chest"], "push", [1, 2, 0], "floor", { shoulders: 1, elbows: 1 }, "3 × 8–12",
    "Lie on the floor, knees bent. Lower until your upper arms touch the floor, pause, and press up. The floor limits the range, which protects the shoulders.",
    [["elbows", "Bruised elbows from hitting the floor", "Lower slowly and let your upper arms land softly."],
     ["shoulders", "Strain when getting the dumbbells into position", "Start seated with the dumbbells on your thighs, then roll back with them held to your chest."]],
    { focus2: ["arms"] }),
  L("db-fly", "Dumbbell Fly", ["chest"], "isolation", [2, 1, 0], "lying", { shoulders: 2, elbows: 1 }, "3 × 10–15",
    "Lie on a flat bench, dumbbells over your chest, elbows slightly bent. Open your arms in a wide arc, then squeeze them back together.",
    [["shoulders", "Chest or front-shoulder strain at the bottom stretch", "Use light weight, keep a fixed bend in the elbows, and stop when your hands reach chest height."],
     ["elbows", "Elbow strain from straightening the arms", "Keep the slight elbow bend the whole set."]]),
  L("db-squeeze-press", "Dumbbell Squeeze Press", ["chest"], "push", [1, 1, 0], "lying", { shoulders: 1, elbows: 1 }, "3 × 10–12",
    "Press the dumbbells together over your chest, then lower and press while squeezing them together the whole time.",
    [["wrists", "Wrist strain", "Palms facing each other, wrists straight."]],
    { focus2: ["arms"] }),
  L("db-pullover", "Dumbbell Pullover", ["chest", "back"], "isolation", [2, 1, 0], "lying", { shoulders: 2, elbows: 1, lowerBack: 1 }, "3 × 10–12",
    "Lie on a bench holding one dumbbell over your chest with both hands. Lower it back over your head with slightly bent arms, then pull it back over your chest.",
    [["shoulders", "Shoulder strain in the overhead stretch", "Only go as far back as feels comfortable. Skip this one if overhead movement hurts."],
     ["lowerBack", "Low back arching", "Keep your ribs down and your lower back on the bench."]]),

  // ---------------- shoulders
  L("db-seated-press", "Seated Dumbbell Shoulder Press", ["shoulders"], "push", [1, 2, 0], "seated", { shoulders: 2, elbows: 1, wrists: 1, lowerBack: 1 }, "3 × 8–10",
    "Bench upright, back supported. Press the dumbbells from shoulder height to overhead, then lower with control.",
    [["shoulders", "Shoulder impingement", "Press slightly in front of your head, not behind it, and don't lower below ear level if it pinches."],
     ["lowerBack", "Lower back arching", "Keep your back flat on the pad and ribs down."]],
    { focus2: ["arms"] }),
  L("db-standing-press", "Standing Dumbbell Overhead Press", ["shoulders", "core"], "push", [2, 2, 0], "standing", { shoulders: 2, lowerBack: 2, wrists: 1 }, "3 × 8–10",
    "Stand tall, brace your core, squeeze your glutes, and press the dumbbells overhead without leaning back.",
    [["lowerBack", "Low back strain from leaning back to finish the press", "Squeeze glutes and brace your abs. If you have to lean, the weight is too heavy."],
     ["shoulders", "Shoulder impingement", "Press slightly forward of your head and keep your shoulders down away from your ears."]],
    { focus2: ["arms"] }),
  L("db-arnold-press", "Arnold Press", ["shoulders"], "push", [2, 2, 0], "seated", { shoulders: 2, elbows: 1 }, "3 × 8–10",
    "Start with palms facing you at chin height. Rotate your palms forward as you press overhead, then reverse on the way down.",
    [["shoulders", "Shoulder irritation from rotating under load", "Use lighter weight than a normal press and keep the rotation smooth. Skip it during shoulder flare-ups."]]),
  L("db-lateral-raise", "Lateral Raise", ["shoulders"], "isolation", [1, 1, 0], "standing", { shoulders: 1, neck: 1 }, "3 × 12–15",
    "Stand tall, slight bend in the elbows. Raise the dumbbells out to shoulder height, leading with the elbows, and lower slowly.",
    [["shoulders", "Impingement from going too high or tipping thumbs down", "Stop at shoulder height and keep thumbs level or slightly up."],
     ["neck", "Neck and trap strain from shrugging", "Keep your shoulders down and use a weight you can lift without swinging."]]),
  L("db-front-raise", "Front Raise", ["shoulders"], "isolation", [1, 1, 0], "standing", { shoulders: 1, lowerBack: 1 }, "3 × 10–12",
    "Raise the dumbbells in front of you to shoulder height, arms nearly straight, then lower slowly.",
    [["lowerBack", "Low back strain from swinging", "Stand tall with abs tight, and go lighter if you have to rock."]]),
  L("db-rear-delt-raise", "Chest-Supported Rear Delt Raise", ["shoulders", "back"], "isolation", [1, 1, 0], "lying", { shoulders: 1, neck: 1 }, "3 × 12–15",
    "Lie chest-down on an incline bench. Raise the dumbbells out to the sides, squeezing between your shoulder blades.",
    [["neck", "Neck strain from craning your head up", "Keep your chin tucked and look down at the floor."]]),
  L("db-shrug", "Dumbbell Shrug", ["back", "shoulders"], "isolation", [1, 1, 0], "standing", { neck: 1, lowerBack: 1 }, "3 × 12–15",
    "Hold heavy dumbbells at your sides and lift your shoulders straight up toward your ears. Pause, then lower.",
    [["neck", "Neck strain from rolling the shoulders", "Lift straight up and down. No rolling."],
     ["lowerBack", "Low back strain from heavy weight", "Stand tall and pick the dumbbells up with a flat back."]],
    { heavy: "When 50 lb gets easy, pause 2 seconds at the top of each rep." }),

  // ---------------- arms
  L("db-curl", "Dumbbell Bicep Curl", ["arms"], "isolation", [1, 1, 0], "standing", { elbows: 1, wrists: 1 }, "3 × 10–12",
    "Elbows at your sides, curl the dumbbells up, squeeze, and lower over about three seconds.",
    [["elbows", "Inner-elbow tendon irritation (golfer's elbow) from heavy, jerky reps", "Use a weight you can lower slowly, and don't swing."],
     ["lowerBack", "Low back strain from swinging", "Stand tall with abs tight, or sit on a bench."]]),
  L("db-hammer-curl", "Hammer Curl", ["arms"], "isolation", [1, 1, 0], "standing", { elbows: 1 }, "3 × 10–12",
    "Palms facing each other, curl up without swinging and lower slowly. Easier on the wrists than a regular curl.",
    [["elbows", "Elbow tendon irritation", "Controlled reps, no swinging."]]),
  L("db-incline-curl", "Incline Dumbbell Curl", ["arms"], "isolation", [2, 1, 0], "seated", { shoulders: 1, elbows: 2 }, "3 × 10–12",
    "Sit back on a bench set at about 45°, arms hanging straight down. Curl without moving your upper arms.",
    [["shoulders", "Biceps tendon strain at the front of the shoulder in the bottom stretch", "Use light weight and don't bounce out of the bottom."],
     ["elbows", "Elbow strain", "Lower slowly to almost straight, not locked."]]),
  L("db-concentration-curl", "Concentration Curl", ["arms"], "isolation", [1, 1, 0], "seated", { elbows: 1 }, "3 × 10–12 per arm",
    "Sit on a bench, elbow braced against the inside of your thigh. Curl up and lower slowly.",
    [["elbows", "Elbow strain", "Smooth reps, no jerking."]], { uni: true }),
  L("db-oh-tri-ext", "Overhead Triceps Extension", ["arms"], "isolation", [1, 1, 0], "seated", { shoulders: 2, elbows: 2 }, "3 × 10–12",
    "Sit tall holding one dumbbell overhead with both hands. Lower it behind your head by bending your elbows, then straighten.",
    [["elbows", "Elbow tendon strain", "Keep elbows pointing forward and lower slowly. Go lighter than you think."],
     ["shoulders", "Shoulder pain in the overhead position", "Skip it if overhead positions hurt; use a skull crusher or close-grip press instead."]],
    { db: false }),
  L("db-skull-crusher", "Dumbbell Skull Crusher", ["arms"], "isolation", [2, 1, 0], "lying", { elbows: 2, wrists: 1 }, "3 × 10–12",
    "Lie on a bench, dumbbells over your chest, palms facing in. Bend only at the elbows to lower them beside your head, then straighten.",
    [["elbows", "Elbow tendinitis", "Lower slowly beside your head, not straight onto it, and keep the weight moderate."]]),
  L("db-close-press", "Close-Grip Dumbbell Press", ["arms", "chest"], "push", [1, 2, 0], "lying", { elbows: 1, wrists: 1, shoulders: 1 }, "3 × 8–12",
    "Lie on a bench, palms facing each other, dumbbells touching. Lower to your chest with elbows close to your sides and press up.",
    [["wrists", "Wrist strain", "Wrists straight, dumbbells pressed together."]]),
  L("db-kickback", "Triceps Kickback", ["arms"], "isolation", [1, 1, 0], "bent", { lowerBack: 1, elbows: 1 }, "3 × 10–12 per arm",
    "One hand and knee on a bench, back flat. Upper arm at your side, straighten your arm back and squeeze.",
    [["lowerBack", "Low back strain from rounding", "Support yourself on the bench and keep your back flat."]], { uni: true }),

  // ---------------- back
  L("db-one-arm-row", "One-Arm Dumbbell Row", ["back"], "pull", [1, 2, 0], "bent", { lowerBack: 1, shoulders: 1 }, "3 × 10 per arm",
    "One hand and knee on a bench, back flat. Pull the dumbbell toward your hip, then lower with control.",
    [["lowerBack", "Low back strain", "Support yourself on the bench, keep your back flat, and don't twist to lift."],
     ["shoulders", "Shoulder strain at the top", "Pull toward your hip, not straight up to your armpit."]],
    { uni: true, focus2: ["arms"], heavy: "When 50 lb gets easy, pause for 2 seconds at the top." }),
  L("db-chest-supported-row", "Chest-Supported Dumbbell Row", ["back"], "pull", [1, 2, 0], "lying", { shoulders: 1 }, "3 × 10–12",
    "Lie chest-down on an incline bench. Row both dumbbells toward your ribs and squeeze your shoulder blades. The bench takes the load off your lower back.",
    [["neck", "Neck strain", "Keep your chin tucked."]], { focus2: ["arms"] }),
  L("db-bent-row", "Bent-Over Dumbbell Row", ["back"], "pull", [2, 2, 0], "bent", { lowerBack: 2, shoulders: 1 }, "3 × 8–10",
    "Hinge forward with a flat back, knees soft. Row both dumbbells toward your hips.",
    [["lowerBack", "Low back strain from holding the bent-over position", "Keep a flat back and braced abs. With any back ache, use the chest-supported row instead."]],
    { focus2: ["arms"] }),
  L("db-renegade-row", "Renegade Row", ["back", "core"], "pull", [3, 3, 0], "floor", { wrists: 2, shoulders: 2, lowerBack: 1 }, "3 × 6 per side",
    "In a push-up position with hands on hex dumbbells, row one dumbbell to your hip while keeping your hips square. Alternate sides.",
    [["wrists", "Wrist strain from balancing on the dumbbells", "Use hex dumbbells that can't roll, keep your wrists straight, or do it from your knees."],
     ["lowerBack", "Sagging hips straining the low back", "Feet wide, glutes squeezed, and hips level."]],
    { focus2: ["shoulders", "arms"] }),

  // ---------------- legs & glutes
  L("db-goblet-squat", "Goblet Squat", ["legs", "glutes"], "squat", [1, 2, 0], "standing", { knees: 2, hips: 1, lowerBack: 1 }, "3 × 10–12",
    "Hold one dumbbell upright against your chest. Squat down between your knees as deep as is comfortable, then stand up.",
    [["knees", "Knee pain from knees caving inward", "Push your knees out over your toes, and only go as deep as feels fine."],
     ["lowerBack", "Low back rounding at the bottom", "Stop just before your tailbone tucks under."]],
    { db: false, focus2: ["core"] }),
  L("db-goblet-box-squat", "Goblet Box Squat", ["legs", "glutes"], "squat", [1, 2, 0], "standing", { knees: 1, hips: 1 }, "3 × 10–12",
    "Same as a goblet squat, but sit back to a bench and touch it lightly before standing. The bench limits depth, which is easier on the knees.",
    [["knees", "Knee pain", "Raise the bench height until it's comfortable, and lower it over the weeks."]], { db: false }),
  L("db-sumo-squat", "Dumbbell Sumo Squat", ["legs", "glutes"], "squat", [1, 2, 0], "standing", { hips: 1, knees: 1 }, "3 × 10–12",
    "Wide stance, toes turned out, one dumbbell hanging between your legs. Squat straight down and stand up.",
    [["hips", "Inner-thigh (groin) strain", "Don't force a wider stance than your hips allow."],
     ["knees", "Knee strain", "Keep your knees pointing the same direction as your toes."]], { db: false }),
  L("db-split-squat", "Dumbbell Split Squat", ["legs", "glutes"], "lunge", [1, 2, 0], "standing", { knees: 2, hips: 1, ankles: 1 }, "3 × 8 per leg",
    "Split stance, back heel up. Lower straight down until the back knee is just above the floor, then press up. Finish one leg, then switch.",
    [["knees", "Front knee pain", "Keep the front shin fairly upright and the knee tracking over your toes. Shorten the range if needed."],
     ["ankles", "Losing balance", "Hold a machine or rack with one hand and one dumbbell in the other."]], { uni: true }),
  L("db-bulgarian", "Bulgarian Split Squat", ["legs", "glutes"], "lunge", [3, 3, 0], "standing", { knees: 2, hips: 2, ankles: 1 }, "3 × 8 per leg",
    "Rear foot on a bench behind you. Lower on the front leg until the thigh is near parallel, then drive up.",
    [["hips", "Hip flexor strain in the back leg", "Use a low bench and don't overstretch the back leg."],
     ["knees", "Front knee pain", "Step the front foot far enough out that your knee stays over your foot."],
     ["ankles", "Falling", "Hold a rack with one hand until your balance is solid."]],
    { uni: true, heavy: "Usually plenty hard with 50 lb or less. Slow the lowering if you need more." }),
  L("db-reverse-lunge", "Dumbbell Reverse Lunge", ["legs", "glutes"], "lunge", [2, 2, 0], "standing", { knees: 1, hips: 1, ankles: 1 }, "3 × 8 per leg",
    "Step back into a lunge, lower until the back knee is just above the floor, and push through the front heel to return. The easiest lunge on the knees.",
    [["knees", "Knee pain", "Take a longer step back and keep the front knee over the foot."],
     ["ankles", "Losing balance", "Start light, or hold one dumbbell at your chest."]], { uni: true }),
  L("db-forward-lunge", "Dumbbell Forward Lunge", ["legs", "glutes"], "lunge", [2, 2, 1], "standing", { knees: 2, ankles: 1 }, "3 × 8 per leg",
    "Step forward into a lunge, lower, then push back to standing.",
    [["knees", "Front knee strain from braking the step", "Take a controlled step, land heel first, and keep the knee behind your toes."]], { uni: true }),
  L("db-walking-lunge", "Dumbbell Walking Lunge", ["legs", "glutes"], "lunge", [2, 3, 1], "standing", { knees: 2, hips: 1, ankles: 1 }, "3 × 10 per leg",
    "Lunge forward and keep going across the floor, alternating legs.",
    [["knees", "Knee strain", "Controlled steps, front knee over the foot."],
     ["ankles", "Tripping", "Clear a straight path and look ahead, not down."]], { uni: true }),
  L("db-lateral-lunge", "Dumbbell Lateral Lunge", ["legs", "glutes"], "lunge", [2, 2, 0], "standing", { knees: 2, hips: 2 }, "3 × 8 per side",
    "Step wide to one side and sit your hips back over that foot, other leg straight. Push back to center.",
    [["hips", "Inner-thigh (groin) strain", "Don't force the width, and sit your hips back rather than just bending the knee."],
     ["knees", "Knee strain on the bent leg", "Keep the knee over the toes and the foot flat."]], { uni: true }),
  L("db-curtsy-lunge", "Dumbbell Curtsy Lunge", ["glutes", "legs"], "lunge", [2, 2, 0], "standing", { knees: 2, hips: 1 }, "3 × 8 per side",
    "Step one leg back and behind the other, like a curtsy, and lower. Works the outer glutes.",
    [["knees", "Knee twisting", "Keep the front knee pointing forward over your foot and use a short step."]], { uni: true }),
  L("db-step-up", "Dumbbell Step-Up", ["legs", "glutes"], "lunge", [2, 2, 0], "standing", { knees: 2, ankles: 1 }, "3 × 10 per leg",
    "Step onto a knee-height (or lower) box or bench and drive up through the top foot without pushing off the bottom one.",
    [["knees", "Knee pain", "Use a lower step and put your whole foot on it."],
     ["ankles", "Missing the step", "Use a stable bench and look at where your foot lands."]], { uni: true }),
  L("db-rdl", "Dumbbell Romanian Deadlift", ["legs", "glutes", "back"], "hinge", [2, 2, 0], "standing", { lowerBack: 2, hips: 1 }, "3 × 8–10",
    "Soften your knees, push your hips straight back, and slide the dumbbells down your thighs until your hamstrings stretch. Stand up by squeezing your glutes.",
    [["lowerBack", "Low back strain from rounding", "Keep a flat back and stop at the hamstring stretch, not at the floor."],
     ["hips", "Hamstring strain", "Lower slowly and don't bounce at the bottom."]],
    { heavy: "50 lb dumbbells may get light. Use a 3-second lowering, or switch to the single-leg version." }),
  L("db-sl-rdl", "Single-Leg Romanian Deadlift", ["legs", "glutes"], "hinge", [3, 2, 0], "standing", { lowerBack: 1, hips: 1, ankles: 2 }, "3 × 8 per leg",
    "Dumbbell in the opposite hand. Hinge on one leg while the other reaches straight back, then stand tall.",
    [["ankles", "Rolling the standing ankle", "Slight knee bend, and lightly hold a rack with your free hand at first."],
     ["lowerBack", "Low back strain from twisting", "Keep hips square to the floor."]], { uni: true }),
  L("db-sumo-deadlift", "Dumbbell Sumo Deadlift", ["glutes", "legs", "back"], "hinge", [1, 2, 0], "standing", { lowerBack: 1, hips: 1, knees: 1 }, "3 × 10",
    "Wide stance, one heavy dumbbell held between your feet. Push your hips back with a flat back, then stand by squeezing your glutes. Keeps the chest more upright than other deadlifts.",
    [["lowerBack", "Low back strain", "Chest up, back flat, and the dumbbell close to your body."]],
    { db: false, heavy: "When one 50 lb dumbbell is easy, hold two dumbbells or slow the lowering." }),
  L("db-deadlift", "Dumbbell Deadlift", ["legs", "glutes", "back"], "hinge", [2, 3, 0], "standing", { lowerBack: 2, hips: 1, knees: 1 }, "4 × 8",
    "Dumbbells at your sides. Hips back, flat back, lower until they pass your knees, then stand up tall. One of the best lifts for bone density.",
    [["lowerBack", "Low back strain", "Brace your abs before each rep, keep your back flat, and keep the weights close to your legs."]],
    { heavy: "Our dumbbells top out around 50 lb. When that's easy, pause at the bottom or use the Smith machine." }),
  L("db-hip-thrust", "Dumbbell Hip Thrust", ["glutes"], "hinge", [1, 2, 0], "lying", { lowerBack: 1, neck: 1 }, "3 × 10–12",
    "Upper back on a bench, dumbbell across your hips. Drive your hips up through your heels and squeeze hard at the top.",
    [["lowerBack", "Low back arching at the top", "Keep your ribs down and finish the lift with your glutes, not your back."],
     ["neck", "Neck strain", "Keep your chin tucked and eyes forward."],
     ["hips", "Bruising from the dumbbell", "Put a folded towel or pad under the dumbbell."]],
    { db: false, heavy: "One 50 lb dumbbell may get light. Add a pause at the top or switch to single-leg." }),
  L("db-glute-bridge", "Dumbbell Glute Bridge", ["glutes"], "hinge", [1, 1, 0], "floor", { lowerBack: 1 }, "3 × 12–15",
    "Lie on your back, knees bent, dumbbell on your hips. Lift your hips, squeeze, and lower slowly.",
    [["lowerBack", "Low back arching", "Squeeze your glutes and keep your ribs down."]], { db: false }),
  L("db-sl-hip-thrust", "Single-Leg Hip Thrust", ["glutes"], "hinge", [2, 2, 0], "lying", { lowerBack: 1, hips: 1 }, "3 × 10 per leg",
    "Upper back on a bench, one foot on the floor and the other knee pulled in. Drive up through the planted heel. Add a dumbbell on the working hip when it gets easy.",
    [["lowerBack", "Low back arching", "Ribs down, and squeeze the glute to finish."]], { uni: true, db: false }),
  L("db-calf-raise", "Dumbbell Calf Raise", ["calves"], "isolation", [1, 1, 0], "standing", { ankles: 2 }, "3 × 12–15",
    "Balls of your feet on a step, dumbbells at your sides. Rise up, pause, and lower your heels slowly.",
    [["ankles", "Achilles tendon or plantar fascia (bottom of the foot) irritation", "Move slowly, don't bounce at the bottom, and skip it while a foot or heel injury is healing."]]),
  L("db-sl-calf-raise", "Single-Leg Calf Raise", ["calves"], "isolation", [2, 1, 0], "standing", { ankles: 2 }, "3 × 10–12 per leg",
    "One foot on a step, the other tucked behind, holding a dumbbell on the working side. Rise up and lower slowly.",
    [["ankles", "Achilles or plantar fascia irritation", "Slow reps, hold something for balance, and skip it with a foot injury."]], { uni: true }),

  // ---------------- core & carries
  L("db-farmer-carry", "Farmer Carry", ["core", "back"], "carry", [1, 2, 0], "standing", { shoulders: 1, lowerBack: 1, wrists: 1 }, "3 × 40 steps",
    "A heavy dumbbell in each hand. Walk tall with short, steady steps, shoulders down.",
    [["ankles", "Dropping a dumbbell on your foot", "Clear the path and set the weights down with a flat back, not by letting go."],
     ["lowerBack", "Low back strain picking up or putting down", "Squat down to grab them with a flat back."]],
    { kind: "carry", focus2: ["arms"], heavy: "When two 50s are easy, walk farther or hold one at your chest." }),
  L("db-suitcase-carry", "Suitcase Carry", ["core"], "carry", [2, 2, 0], "standing", { lowerBack: 1, shoulders: 1 }, "3 × 30 steps per side",
    "One heavy dumbbell in one hand. Walk tall without leaning toward it. Switch hands each set.",
    [["lowerBack", "Low back strain from leaning", "Shoulders level and abs braced. Go lighter if you lean."]], { kind: "carry", uni: true, db: false }),
  L("db-russian-twist", "Weighted Russian Twist", ["core"], "rotation", [2, 2, 0], "floor", { lowerBack: 2 }, "3 × 20 total",
    "Sit with knees bent, lean back slightly, holding a dumbbell at your chest. Rotate side to side.",
    [["lowerBack", "Low back strain from rounding and twisting under load", "Sit tall, rotate your chest rather than just your arms, and keep it light. Skip during back aches."]], { db: false }),
  L("db-weighted-dead-bug", "Weighted Dead Bug", ["core"], "core", [2, 1, 0], "floor", { shoulders: 1 }, "3 × 8 per side",
    "On your back holding a light dumbbell overhead in both hands, knees over hips. Lower opposite legs away while your lower back stays pressed down.",
    [["lowerBack", "Low back arching off the floor", "Only lower your legs as far as you can keep your back flat."]], { db: false }),
  L("db-side-bend", "Dumbbell Side Bend", ["core"], "core", [1, 1, 0], "standing", { lowerBack: 1 }, "3 × 12 per side",
    "One dumbbell at your side. Bend sideways toward it, then pull back up using the opposite side of your waist.",
    [["lowerBack", "Low back strain from heavy weight or twisting", "Moderate weight, slow reps, bend straight sideways."]], { uni: true, db: false }),
  L("db-woodchop", "Dumbbell Woodchop", ["core"], "rotation", [2, 2, 0], "standing", { lowerBack: 1, shoulders: 1, knees: 1 }, "3 × 10 per side",
    "Hold one dumbbell with both hands by one hip. Swing it diagonally up across your body, pivoting on the back foot, then lower with control.",
    [["lowerBack", "Low back strain from twisting", "Pivot your back foot and turn your hips with you."],
     ["knees", "Knee twisting", "Let the back heel lift and turn as you rotate."]], { db: false }),
  L("db-situp", "Dumbbell Sit-Up", ["core"], "core", [2, 2, 0], "floor", { neck: 1, lowerBack: 1 }, "3 × 12–15",
    "Feet anchored, dumbbell held at your chest. Curl all the way up and lower slowly.",
    [["neck", "Neck strain", "Keep the dumbbell at your chest and your chin slightly tucked. Don't pull with your head."],
     ["lowerBack", "Low back strain", "Lower slowly, one segment of your spine at a time."]], { db: false }),

  // ---------------- full body & power
  L("db-thruster", "Dumbbell Thruster", ["legs", "shoulders", "glutes"], "power", [2, 3, 0], "standing", { knees: 2, shoulders: 2, lowerBack: 1 }, "3 × 8–10",
    "Dumbbells at your shoulders. Squat, then drive up and use that momentum to press the dumbbells overhead in one movement.",
    [["lowerBack", "Low back arching overhead", "Squeeze your glutes as you press, and finish with your biceps by your ears."],
     ["knees", "Knee strain", "Squat only as deep as is comfortable."]], { focus2: ["core"] }),
  L("db-swing", "Single Dumbbell Swing", ["glutes", "legs"], "power", [2, 3, 0], "standing", { lowerBack: 2, shoulders: 1 }, "3 × 15",
    "Hold one dumbbell by the end with both hands. Hinge, swing it back between your legs, then snap your hips forward to swing it to chest height.",
    [["lowerBack", "Low back strain from squatting or lifting with your arms", "It's a hip snap: hinge back, then drive your hips forward. Your arms just hold on."],
     ["shoulders", "Losing your grip", "Hold the dumbbell end firmly with both hands and give yourself clear space."]], { db: false, focus2: ["core"] }),
  L("db-clean-press", "Dumbbell Clean and Press", ["shoulders", "legs", "back"], "power", [3, 3, 0], "standing", { wrists: 1, shoulders: 2, lowerBack: 2, knees: 1 }, "3 × 6",
    "From the floor or knee height, pull the dumbbells up and catch them at your shoulders, then press overhead.",
    [["lowerBack", "Low back strain", "Start with a flat back and let your legs drive."],
     ["wrists", "Wrist strain on the catch", "Catch with soft elbows and relaxed wrists. Learn it light first."]]),
  L("db-jump-squat", "Dumbbell Jump Squat", ["legs", "glutes"], "power", [3, 3, 2], "standing", { knees: 2, ankles: 2, hips: 1 }, "3 × 6–8",
    "Light dumbbells at your sides. Squat to a comfortable depth, jump up, land softly with bent knees, and reset before the next rep. The impact helps build bone density.",
    [["knees", "Knee pain from hard landings", "Land quietly with bent knees, hips back."],
     ["ankles", "Ankle or foot injury from the impact", "Skip it with any foot, ankle, or knee injury. Use light dumbbells, or none."]])
];

// Movement pattern for each plan exercise (for ranking swaps).
export const PLAN_PATTERN = {
  "a-mon-cp": "push", "a-mon-inc": "push", "a-mon-sp": "push", "a-mon-lat": "isolation", "a-mon-push": "isolation", "a-mon-fly": "isolation",
  "a-tue-pd": "pull", "a-tue-row": "pull", "a-tue-pu": "pull", "a-tue-bext": "hinge", "a-tue-rdelt": "isolation", "a-tue-curl": "isolation",
  "a-wed-ht": "hinge", "a-wed-dl": "hinge", "a-wed-sq": "squat", "a-wed-lunge": "lunge", "a-wed-curl": "isolation", "a-wed-ext": "isolation", "a-wed-abd": "isolation",
  "a-thu-bug": "core", "a-thu-pallof": "rotation", "a-thu-plank": "core", "a-thu-goblet": "squat", "a-thu-farmer": "carry", "a-thu-calf": "isolation",
  "b-mon-inc": "push", "b-mon-fly": "isolation", "b-mon-sp": "push", "b-mon-clat": "isolation", "b-mon-dip": "push", "b-mon-ohext": "isolation",
  "b-tue-cgpd": "pull", "b-tue-csrow": "pull", "b-tue-sapd": "pull", "b-tue-bext": "hinge", "b-tue-face": "pull", "b-tue-hammer": "isolation",
  "b-wed-ht": "hinge", "b-wed-rdl": "hinge", "b-wed-lp": "squat", "b-wed-split": "lunge", "b-wed-curl": "isolation", "b-wed-add": "isolation", "b-wed-abd": "isolation",
  "b-thu-rot": "rotation", "b-thu-knee": "core", "b-thu-suit": "carry", "b-thu-hold": "core", "b-thu-goblet": "squat", "b-thu-calf": "isolation"
};

// Stretches to suggest for a library exercise, by its main focus.
export const STRETCH_BY_FOCUS = {
  chest: ["chest", "crossbody"], shoulders: ["crossbody", "circles"], arms: ["triceps", "bicep"], back: ["lat", "twist"],
  core: ["twist", "backarch"], glutes: ["fig4", "hipflex"], legs: ["quad", "hamstring"], calves: ["calf", "ankle"], cardio: ["quad", "calf"]
};

// Fill in defaults so entries typed into the app (machines added later) work like built-in ones.
export function normalizeLib(e) {
  return {
    focus: [], focus2: [], pattern: "", difficulty: 1, effort: 2, impact: 0, position: "", unilateral: false,
    joints: {}, sr: "3 × 10", how: e.notes || "", risks: [], kind: "load", db: false, heavy: "", equip: "machine", ...e
  };
}
